//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTrackingServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTasks
    {
        public ProjectTasks()
        {
            this.ManagerComments = new HashSet<ManagerComments>();
        }
    
        public int ProjectTaskID { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public Nullable<System.DateTime> TaskStartDate { get; set; }
        public Nullable<System.DateTime> TaskEndDate { get; set; }
        public Nullable<int> TaskCompletion { get; set; }
        public Nullable<int> UserStoryID { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual ICollection<ManagerComments> ManagerComments { get; set; }
        public virtual UserStories UserStories { get; set; }
    }
}
